### ISSUE TITLE
Collect Requirements and Risks

### ISSUE THREAD

**Issue by LeahKorol** [LeahKorol/remez#4]
**Overview:**
This Issue tracks the collection of project requirements and risk factors. All related meeting notes and requirements will be documented here.

**Related Documents:**
- [Requirements & Risks Collection Document](https://docs.google.com/document/d/1EdAVgKabf5Jlk2G5Ji06qwOjRXobj3nZ32MOaQRQMSw/edit?tab=t.0)

**Tasks:**
1. Review the document and add new requirements or risks as they arise.
2. Meet with Dr. Gurelik to finalize any open requirements.
3. Identify and assess potential risks for the project.

**Status:**
- [x] -  Review current document
- [x] -  Meet with Dr. Gurelik
- [x] -  Update document with new requirements/risk factors
